AWSTemplateFormatVersion: "2010-09-09"
Description: Get Weather and air quality lambda

Parameters:
  Application:
    Type: String
  OpenWeatherApiKeySecretArn:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
  LambdaName:
    Type: String
  LambdaHandler:
    Type: String
  LambdaBucketName:
    Type: String
  LambdaZipFile:
    Type: String
  OpenWeatherApiKeySecretName:
    Type: String

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: read-open-weather-api-key-secret
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref OpenWeatherApiKeySecretArn

      
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
     LogGroupName: !Join ['/', ['/aws/lambda', !Ref LambdaFunction]]
     RetentionInDays: 7 # days
                
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Application}-${Environment}-${LambdaName}
      Code:
        S3Bucket: !Sub ${LambdaBucketName}
        S3Key: !Sub ${LambdaZipFile}
      Handler: !Sub ${LambdaHandler}
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Runtime: nodejs16.x
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          OPEN_WEATHER_APIKEY_SECRET_NAME: !Ref OpenWeatherApiKeySecretName
      Layers:
        - arn:aws:lambda:eu-west-1:015030872274:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2

      
Outputs:
  LambdaFunctionArn:
    Description: Lambda Arn
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-get-weather-and-air-quality-lambda
  
  
  