AWSTemplateFormatVersion: "2010-09-09"
Description: open weather api key secret

Resources:  
  OpenWeatherApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: open weather api key secret
      Name: open-weather-api-key-secret
