AWSTemplateFormatVersion: "2010-09-09"
Description: open weather api key secret

Parameters:
  OpenWeatherApiKeySecretName:
    Type: String
    Default: open-weather-api-key-secret

Resources:  
  OpenWeatherApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: open weather api key secret
      Name: !Ref OpenWeatherApiKeySecretName

Outputs:
  OpenWeatherApiKeySecretArn:
    Description: OpenWeatherApiKeySecret Arn
    Value: !Ref OpenWeatherApiKeySecret
    Export:
      Name: !Sub ${AWS::StackName}-open-weather-api-key-secret

    OpenWeatherApiKeySecretName:
      Description: OpenWeatherApiKeySecret Name
      Value: !Ref OpenWeatherApiKeySecretName
      Export:
        Name: !Sub ${AWS::StackName}-open-weather-api-key-secret-name
        