AWSTemplateFormatVersion: "2010-09-09"
Description: open weather api key secret

Parameters:
  KeySecretName:
    Type: String
    Default: open-weather-api-key-secret

Resources:  
  OpenWeatherApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: open weather api key secret
      Name: !Ref KeySecretName

Outputs:
  OpenWeatherApiKeySecretArn:
    Description: OpenWeatherApiKeySecret Arn
    Value: !Ref OpenWeatherApiKeySecret
    Export:
      Name: !Sub ${AWS::StackName}-open-weather-api-key-secret

  OpenWeatherApiKeySecretName:
    Description: OpenWeatherApiKeySecret Name
    Value: !Ref KeySecretName
    Export:
      Name: !Sub ${AWS::StackName}-open-weather-api-key-secret-name
        